# https://github.com/embarkmobile/android-maven-example
language: java
jdk: oraclejdk7
before_install:
    # Install base Android SDK
    - sudo apt-get update -qq
    - sudo apt-get install -qq libstdc++6:i386 lib32z1
    - export COMPONENTS=build-tools-19.0.1,android-19,sysimg-19,extra-android-support
    - curl -L https://raw.github.com/embarkmobile/android-sdk-installer/master/android-sdk-installer | bash /dev/stdin --install=$COMPONENTS
    - source ~/.android-sdk-installer/env
    # setup gradle wrapper
    # Create and start emulator
    #- curl -LO https://raw.github.com/embarkmobile/android-maven-example/master/wait_for_emulator ; chmod +x wait_for_emulator
    #- echo no | android create avd --force -n test -t android-16 --abi armeabi-v7a
    #- emulator -avd test -no-skin -no-audio -no-window &
    #- ./wait_for_emulator

script: ./gradlew --no-color assembleDebug
